//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們的建議如下:.
        /// </summary>
        internal static string Home_Index_HeaderText {
            get {
                return ResourceManager.GetString("Home_Index_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您可以看關於我們,了解我們的相關資訊,以及我們提供的服務種類.
        /// </summary>
        internal static string Home_Index_ListDescription1 {
            get {
                return ResourceManager.GetString("Home_Index_ListDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在成功案例裡面,你可以看到我們以往完成的任務.
        /// </summary>
        internal static string Home_Index_ListDescription2 {
            get {
                return ResourceManager.GetString("Home_Index_ListDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無論您需要什麼樣的服務,聯絡我們你總是可以得到解答.
        /// </summary>
        internal static string Home_Index_ListDescription3 {
            get {
                return ResourceManager.GetString("Home_Index_ListDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 了解725Soft軟體科技.
        /// </summary>
        internal static string Home_Index_ListTitle1 {
            get {
                return ResourceManager.GetString("Home_Index_ListTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 看成功案例.
        /// </summary>
        internal static string Home_Index_ListTitle2 {
            get {
                return ResourceManager.GetString("Home_Index_ListTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡我們.
        /// </summary>
        internal static string Home_Index_ListTitle3 {
            get {
                return ResourceManager.GetString("Home_Index_ListTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎來到725Soft 軟體科技.
        /// </summary>
        internal static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於我們.
        /// </summary>
        internal static string Layout_About_LinkText {
            get {
                return ResourceManager.GetString("Layout_About_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功案例.
        /// </summary>
        internal static string Layout_Case_LinkText {
            get {
                return ResourceManager.GetString("Layout_Case_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡我們.
        /// </summary>
        internal static string Layout_Contact_LinkText {
            get {
                return ResourceManager.GetString("Layout_Contact_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 725Soft 軟體科技..
        /// </summary>
        internal static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們是一間新創的IT服務公司,擁有很多軟體開發的經驗,希望能夠提供給所有需要我們的客戶最棒的服務..
        /// </summary>
        internal static string Layout_Description {
            get {
                return ResourceManager.GetString("Layout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        internal static string Layout_Home_LinkText {
            get {
                return ResourceManager.GetString("Layout_Home_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Layout_Message {
            get {
                return ResourceManager.GetString("Layout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服務項目.
        /// </summary>
        internal static string Layout_Service_LinkText {
            get {
                return ResourceManager.GetString("Layout_Service_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 725Soft 軟體科技. 我們提供365天+360度的技術支援.
        /// </summary>
        internal static string Layout_SiteTitle {
            get {
                return ResourceManager.GetString("Layout_SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
    }
}
