//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 725軟體科技。.
        /// </summary>
        internal static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        internal static string Layout_LinkAbout_Text {
            get {
                return ResourceManager.GetString("Layout_LinkAbout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案例.
        /// </summary>
        internal static string Layout_LinkCase_Text {
            get {
                return ResourceManager.GetString("Layout_LinkCase_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡我們.
        /// </summary>
        internal static string Layout_LinkContact_Text {
            get {
                return ResourceManager.GetString("Layout_LinkContact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        internal static string Layout_LinkHome_Text {
            get {
                return ResourceManager.GetString("Layout_LinkHome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服務.
        /// </summary>
        internal static string Layout_LinkService_Text {
            get {
                return ResourceManager.GetString("Layout_LinkService_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 725軟體科技-我們提供全時全方位的技術服務。.
        /// </summary>
        internal static string Layout_SiteTitle {
            get {
                return ResourceManager.GetString("Layout_SiteTitle", resourceCulture);
            }
        }
    }
}
