//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 725軟體科技的名稱由來？.
        /// </summary>
        internal static string About_Header_Title {
            get {
                return ResourceManager.GetString("About_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 725軟體科技  一年365天全年無休｡.
        /// </summary>
        internal static string About_List_Description1 {
            get {
                return ResourceManager.GetString("About_List_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 725軟體科技  提供360度的全方位服務｡.
        /// </summary>
        internal static string About_List_Description2 {
            get {
                return ResourceManager.GetString("About_List_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365天加上360度等於 725軟體科技｡.
        /// </summary>
        internal static string About_List_Description3 {
            get {
                return ResourceManager.GetString("About_List_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365天.
        /// </summary>
        internal static string About_List_Title1 {
            get {
                return ResourceManager.GetString("About_List_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360度.
        /// </summary>
        internal static string About_List_Title2 {
            get {
                return ResourceManager.GetString("About_List_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 725軟體科技.
        /// </summary>
        internal static string About_List_Title3 {
            get {
                return ResourceManager.GetString("About_List_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提供您最即時的技術支援｡.
        /// </summary>
        internal static string About_Message {
            get {
                return ResourceManager.GetString("About_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎來到 725軟體科技.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們已經成功完成這些任務：.
        /// </summary>
        internal static string Cases_Header_Title {
            get {
                return ResourceManager.GetString("Cases_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們有相當多的成功經驗與案例｡.
        /// </summary>
        internal static string Cases_Message {
            get {
                return ResourceManager.GetString("Cases_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎來到 725軟體科技.
        /// </summary>
        internal static string Cases_Title {
            get {
                return ResourceManager.GetString("Cases_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台北市大安區敦化南路二段｡.
        /// </summary>
        internal static string Contact_Address_Description {
            get {
                return ResourceManager.GetString("Contact_Address_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址：.
        /// </summary>
        internal static string Contact_Address_Title {
            get {
                return ResourceManager.GetString("Contact_Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手機號碼：.
        /// </summary>
        internal static string Contact_CellPhone_Title {
            get {
                return ResourceManager.GetString("Contact_CellPhone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子郵件：.
        /// </summary>
        internal static string Contact_Email_Title {
            get {
                return ResourceManager.GetString("Contact_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡資訊：.
        /// </summary>
        internal static string Contact_Header_Title {
            get {
                return ResourceManager.GetString("Contact_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 永遠歡迎您與我們聯絡｡.
        /// </summary>
        internal static string Contact_Message {
            get {
                return ResourceManager.GetString("Contact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話號碼：.
        /// </summary>
        internal static string Contact_Phone_Title {
            get {
                return ResourceManager.GetString("Contact_Phone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支援服務：.
        /// </summary>
        internal static string Contact_Support_Email_Title {
            get {
                return ResourceManager.GetString("Contact_Support_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎來到 725軟體科技.
        /// </summary>
        internal static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們的建議如下:.
        /// </summary>
        internal static string Index_Header {
            get {
                return ResourceManager.GetString("Index_Header", resourceCulture);
=======
        ///   Looks up a localized string similar to 我們的建議如下:.
        /// </summary>
        internal static string Home_Index_HeaderText {
            get {
                return ResourceManager.GetString("Home_Index_HeaderText", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 您可以從關於我中，了解我們的經營理念與創立的宗旨｡.
        /// </summary>
        internal static string Index_List_Description1 {
            get {
                return ResourceManager.GetString("Index_List_Description1", resourceCulture);
=======
        ///   Looks up a localized string similar to 您可以看關於我們,了解我們的相關資訊,以及我們提供的服務種類.
        /// </summary>
        internal static string Home_Index_ListDescription1 {
            get {
                return ResourceManager.GetString("Home_Index_ListDescription1", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 您可以在服務中看到我們提供的所有服務項目｡.
        /// </summary>
        internal static string Index_List_Description2 {
            get {
                return ResourceManager.GetString("Index_List_Description2", resourceCulture);
=======
        ///   Looks up a localized string similar to 在成功案例裡面,你可以看到我們以往完成的任務.
        /// </summary>
        internal static string Home_Index_ListDescription2 {
            get {
                return ResourceManager.GetString("Home_Index_ListDescription2", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 您可以在案例中看到我們過去的成功經驗｡.
        /// </summary>
        internal static string Index_List_Description3 {
            get {
                return ResourceManager.GetString("Index_List_Description3", resourceCulture);
=======
        ///   Looks up a localized string similar to 無論您需要什麼樣的服務,聯絡我們你總是可以得到解答.
        /// </summary>
        internal static string Home_Index_ListDescription3 {
            get {
                return ResourceManager.GetString("Home_Index_ListDescription3", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 不論您有任何的問題都隨時歡迎您與我們聯絡，您總是可以得到您要的答案｡.
        /// </summary>
        internal static string Index_List_Description4 {
            get {
                return ResourceManager.GetString("Index_List_Description4", resourceCulture);
=======
        ///   Looks up a localized string similar to 了解725Soft軟體科技.
        /// </summary>
        internal static string Home_Index_ListTitle1 {
            get {
                return ResourceManager.GetString("Home_Index_ListTitle1", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 了解我們的背景.
        /// </summary>
        internal static string Index_List_Header1 {
            get {
                return ResourceManager.GetString("Index_List_Header1", resourceCulture);
=======
        ///   Looks up a localized string similar to 看成功案例.
        /// </summary>
        internal static string Home_Index_ListTitle2 {
            get {
                return ResourceManager.GetString("Home_Index_ListTitle2", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 查詢我們提供的服務.
        /// </summary>
        internal static string Index_List_Header2 {
            get {
                return ResourceManager.GetString("Index_List_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 參考我們的成功案例.
        /// </summary>
        internal static string Index_List_Header3 {
            get {
                return ResourceManager.GetString("Index_List_Header3", resourceCulture);
=======
        ///   Looks up a localized string similar to 聯絡我們.
        /// </summary>
        internal static string Home_Index_ListTitle3 {
            get {
                return ResourceManager.GetString("Home_Index_ListTitle3", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 馬上聯絡我們.
        /// </summary>
        internal static string Index_List_Header4 {
            get {
                return ResourceManager.GetString("Index_List_Header4", resourceCulture);
=======
        ///   Looks up a localized string similar to 歡迎來到725Soft 軟體科技.
        /// </summary>
        internal static string Home_Index_Title {
            get {
                return ResourceManager.GetString("Home_Index_Title", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 您的最佳技術服務夥伴｡.
        /// </summary>
        internal static string Index_Message {
            get {
                return ResourceManager.GetString("Index_Message", resourceCulture);
=======
        ///   Looks up a localized string similar to 關於我們.
        /// </summary>
        internal static string Layout_About_LinkText {
            get {
                return ResourceManager.GetString("Layout_About_LinkText", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 歡迎來到 725軟體科技.
        /// </summary>
        internal static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
=======
        ///   Looks up a localized string similar to 成功案例.
        /// </summary>
        internal static string Layout_Case_LinkText {
            get {
                return ResourceManager.GetString("Layout_Case_LinkText", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 725軟體科技    版權所有.
        /// </summary>
        internal static string Layout_CopyRight_Left {
            get {
                return ResourceManager.GetString("Layout_CopyRight_Left", resourceCulture);
=======
        ///   Looks up a localized string similar to 聯絡我們.
        /// </summary>
        internal static string Layout_Contact_LinkText {
            get {
                return ResourceManager.GetString("Layout_Contact_LinkText", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 725Soft Taiwan Inc. All rights reserved..
        /// </summary>
        internal static string Layout_CopyRight_Right {
            get {
                return ResourceManager.GetString("Layout_CopyRight_Right", resourceCulture);
=======
        ///   Looks up a localized string similar to 725Soft 軟體科技..
        /// </summary>
        internal static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 我們是一間新創軟體服務公司，擁有許多軟體開發經驗，希望能提供給所有客戶最好的技術服務｡.
=======
        ///   Looks up a localized string similar to 我們是一間新創的IT服務公司,擁有很多軟體開發的經驗,希望能夠提供給所有需要我們的客戶最棒的服務..
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
        /// </summary>
        internal static string Layout_Description {
            get {
                return ResourceManager.GetString("Layout_Description", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 關於.
        /// </summary>
        internal static string Layout_LinkText_About {
            get {
                return ResourceManager.GetString("Layout_LinkText_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案例.
        /// </summary>
        internal static string Layout_LinkText_Cases {
            get {
                return ResourceManager.GetString("Layout_LinkText_Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡我們.
        /// </summary>
        internal static string Layout_LinkText_Contact {
            get {
                return ResourceManager.GetString("Layout_LinkText_Contact", resourceCulture);
=======
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        internal static string Layout_Home_LinkText {
            get {
                return ResourceManager.GetString("Layout_Home_LinkText", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        internal static string Layout_LinkText_Home {
            get {
                return ResourceManager.GetString("Layout_LinkText_Home", resourceCulture);
=======
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Layout_Message {
            get {
                return ResourceManager.GetString("Layout_Message", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 服務.
        /// </summary>
        internal static string Layout_LinkText_Services {
            get {
                return ResourceManager.GetString("Layout_LinkText_Services", resourceCulture);
=======
        ///   Looks up a localized string similar to 服務項目.
        /// </summary>
        internal static string Layout_Service_LinkText {
            get {
                return ResourceManager.GetString("Layout_Service_LinkText", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 725軟體科技  我們提供全天候全方位的技術服務｡.
=======
        ///   Looks up a localized string similar to 725Soft 軟體科技. 我們提供365天+360度的技術支援.
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
        /// </summary>
        internal static string Layout_SiteTitle {
            get {
                return ResourceManager.GetString("Layout_SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to 我們提供如此多的服務：.
        /// </summary>
        internal static string Services_Header_Title {
            get {
                return ResourceManager.GetString("Services_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業網站規劃, 網頁設計, 論壇設計, 企業ERP方案, CRM方案.
        /// </summary>
        internal static string Services_List_Description1 {
            get {
                return ResourceManager.GetString("Services_List_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料庫規劃與設計, 資料分析, 系統資料轉換, 商業智慧方案.
        /// </summary>
        internal static string Services_List_Description2 {
            get {
                return ResourceManager.GetString("Services_List_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 單機程式開發, VBA開發.
        /// </summary>
        internal static string Services_List_Description3 {
            get {
                return ResourceManager.GetString("Services_List_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash, 影像美工, 文字編輯.
        /// </summary>
        internal static string Services_List_Description4 {
            get {
                return ResourceManager.GetString("Services_List_Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 網路應用.
        /// </summary>
        internal static string Services_List_Title1 {
            get {
                return ResourceManager.GetString("Services_List_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料處理.
        /// </summary>
        internal static string Services_List_Title2 {
            get {
                return ResourceManager.GetString("Services_List_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 單機程式開發.
        /// </summary>
        internal static string Services_List_Title3 {
            get {
                return ResourceManager.GetString("Services_List_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string Services_List_Title4 {
            get {
                return ResourceManager.GetString("Services_List_Title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我們提供各種您所需要的技術服務｡.
        /// </summary>
        internal static string Services_Message {
            get {
                return ResourceManager.GetString("Services_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎來到 725軟體科技.
        /// </summary>
        internal static string Services_Title {
            get {
                return ResourceManager.GetString("Services_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歡迎來到 725軟體科技.
        /// </summary>
        internal static string Site_Title {
            get {
                return ResourceManager.GetString("Site_Title", resourceCulture);
=======
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
>>>>>>> 6c9bb20d7e8ac432917909174e3e087fd5e4f587
            }
        }
    }
}
